# Use Node.js v22.4.1 as the base image
FROM node:22.4.1

# Install TypeScript globally
RUN npm install -g typescript

# Set the working directory inside the container
WORKDIR /app

# Keep the command line open for user interaction
CMD ["bash"]
