import { readFileSync } from 'fs';
import { join } from 'path';

describe('generated-constants.ts', () => {
  const EXPECTED_CONTENT = `// This file is a placeholder for development.
// During build, it gets overwritten with the actual PostHog key.
// DO NOT edit this file manually - changes will be lost during build.

export const POSTHOG_KEY = process.env.PROMPTFOO_POSTHOG_KEY || '';
`;

  it('should remain unchanged from the placeholder version', () => {
    const filePath = join(process.cwd(), 'src', 'generated-constants.ts');
    const actualContent = readFileSync(filePath, 'utf-8');

    // Normalize line endings for cross-platform compatibility
    const normalizedActual = actualContent.replace(/\r\n/g, '\n');
    const normalizedExpected = EXPECTED_CONTENT.replace(/\r\n/g, '\n');

    expect(normalizedActual).toBe(normalizedExpected);
  });
});
