import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { MediaEmptyState } from './MediaEmptyState';

describe('MediaEmptyState', () => {
  describe('when hasFilters is false', () => {
    it('renders the initial empty state message', () => {
      render(<MediaEmptyState hasFilters={false} />);

      expect(screen.getByText('No media files yet')).toBeInTheDocument();
      expect(
        screen.getByText(/Media generated by your evaluations will appear here/),
      ).toBeInTheDocument();
    });

    it('renders the documentation link', () => {
      render(<MediaEmptyState hasFilters={false} />);

      const link = screen.getByRole('link', { name: /View Providers Docs/i });
      expect(link).toBeInTheDocument();
      expect(link).toHaveAttribute('href', 'https://www.promptfoo.dev/docs/providers/');
      expect(link).toHaveAttribute('target', '_blank');
      expect(link).toHaveAttribute('rel', 'noopener noreferrer');
    });

    it('does not render the clear filters button', () => {
      render(<MediaEmptyState hasFilters={false} />);

      expect(screen.queryByRole('button', { name: /Clear Filters/i })).not.toBeInTheDocument();
    });

    it('renders the image icon', () => {
      const { container } = render(<MediaEmptyState hasFilters={false} />);

      // Icon is rendered as SVG
      const svgIcon = container.querySelector('svg');
      expect(svgIcon).toBeInTheDocument();
    });
  });

  describe('when hasFilters is true', () => {
    it('renders the filtered empty state message', () => {
      render(<MediaEmptyState hasFilters={true} />);

      expect(screen.getByText('No media found')).toBeInTheDocument();
      expect(screen.getByText('No media matches your current filters.')).toBeInTheDocument();
    });

    it('does not render the documentation link', () => {
      render(<MediaEmptyState hasFilters={true} />);

      expect(screen.queryByRole('link', { name: /View Providers Docs/i })).not.toBeInTheDocument();
    });

    it('renders the clear filters button when onClearFilters is provided', () => {
      const handleClearFilters = vi.fn();
      render(<MediaEmptyState hasFilters={true} onClearFilters={handleClearFilters} />);

      const button = screen.getByRole('button', { name: /Clear Filters/i });
      expect(button).toBeInTheDocument();
    });

    it('calls onClearFilters when button is clicked', () => {
      const handleClearFilters = vi.fn();
      render(<MediaEmptyState hasFilters={true} onClearFilters={handleClearFilters} />);

      const button = screen.getByRole('button', { name: /Clear Filters/i });
      fireEvent.click(button);

      expect(handleClearFilters).toHaveBeenCalledTimes(1);
    });

    it('does not render the clear filters button when onClearFilters is not provided', () => {
      render(<MediaEmptyState hasFilters={true} />);

      expect(screen.queryByRole('button', { name: /Clear Filters/i })).not.toBeInTheDocument();
    });
  });

  it('applies correct container styling', () => {
    const { container } = render(<MediaEmptyState hasFilters={false} />);

    const wrapper = container.firstChild;
    expect(wrapper).toHaveClass('flex', 'flex-col', 'items-center', 'justify-center');
    expect(wrapper).toHaveClass('rounded-xl', 'border', 'border-dashed');
  });
});
