import { Button } from '@app/components/ui/button';
import { ImageIcon } from 'lucide-react';

interface MediaEmptyStateProps {
  hasFilters: boolean;
  onClearFilters?: () => void;
}

export function MediaEmptyState({ hasFilters, onClearFilters }: MediaEmptyStateProps) {
  if (hasFilters) {
    return (
      <div className="flex flex-col items-center justify-center py-16 px-4 rounded-xl bg-muted/30 border border-dashed border-border">
        <div className="rounded-full bg-muted p-4 mb-4">
          <ImageIcon className="h-8 w-8 text-muted-foreground" />
        </div>
        <h3 className="text-lg font-semibold mb-1">No media found</h3>
        <p className="text-sm text-muted-foreground text-center mb-4">
          No media matches your current filters.
        </p>
        {onClearFilters && (
          <Button variant="outline" onClick={onClearFilters}>
            Clear Filters
          </Button>
        )}
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center justify-center py-16 px-4 rounded-xl bg-muted/30 border border-dashed border-border">
      <div className="rounded-full bg-muted p-4 mb-4">
        <ImageIcon className="h-8 w-8 text-muted-foreground" />
      </div>
      <h3 className="text-lg font-semibold mb-1">No media files yet</h3>
      <p className="text-sm text-muted-foreground text-center max-w-md">
        Media generated by your evaluations will appear here. Run an eval with an image, video, or
        audio provider to get started.
      </p>
      <a
        href="https://www.promptfoo.dev/docs/providers/"
        target="_blank"
        rel="noopener noreferrer"
        className="mt-4 text-sm text-primary hover:underline"
      >
        View Providers Docs →
      </a>
    </div>
  );
}
