#!/usr/bin/env python3
"""Create an isolated Codex home for the Computer Use dogfood eval."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

MARKER_NAME = ".promptfoo-computer-use-fixture"
PLUGIN_NAME = "computer-use"
SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plugin-dir", required=True, type=Path)
    parser.add_argument("--codex-home", required=True, type=Path)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def resolve_launcher(plugin_dir: Path) -> Path:
    manifest_path = plugin_dir / ".codex-plugin" / "plugin.json"
    mcp_path = plugin_dir / ".mcp.json"
    if not manifest_path.is_file() or not mcp_path.is_file():
        raise ValueError(
            "plugin directory must contain .codex-plugin/plugin.json and .mcp.json"
        )

    manifest = json.loads(manifest_path.read_text())
    if manifest.get("name") != PLUGIN_NAME:
        raise ValueError(
            f"expected {PLUGIN_NAME!r} plugin, found {manifest.get('name')!r}"
        )

    mcp_config = json.loads(mcp_path.read_text())
    server = mcp_config.get("mcpServers", {}).get(PLUGIN_NAME, {})
    command = server.get("command")
    if not isinstance(command, str) or not command:
        raise ValueError("computer-use MCP config must contain a command")

    launcher = (plugin_dir / command).resolve()
    try:
        launcher.relative_to(plugin_dir)
    except ValueError:
        raise ValueError(
            "computer-use MCP launcher must be a file inside the plugin directory"
        ) from None
    if not launcher.is_file():
        raise ValueError(
            "computer-use MCP launcher must be a file inside the plugin directory"
        )
    if launcher.stat().st_mode & 0o111 == 0:
        raise ValueError("computer-use MCP launcher must be executable")
    return launcher


def resolve_marketplace(plugin_dir: Path) -> tuple[str, Path]:
    marketplace_root = plugin_dir.parent.parent
    marketplace_path = marketplace_root / ".agents" / "plugins" / "marketplace.json"
    if not marketplace_path.is_file():
        raise ValueError("plugin directory must belong to a bundled marketplace root")

    marketplace = json.loads(marketplace_path.read_text())
    marketplace_name = marketplace.get("name")
    if not isinstance(marketplace_name, str) or not SAFE_NAME_RE.fullmatch(
        marketplace_name
    ):
        raise ValueError(
            "marketplace name may contain only letters, numbers, dots, underscores, and dashes"
        )

    for entry in marketplace.get("plugins", []):
        source = entry.get("source", {})
        source_path = source.get("path")
        if entry.get("name") == PLUGIN_NAME and isinstance(source_path, str):
            if (marketplace_root / source_path).resolve() == plugin_dir:
                return marketplace_name, marketplace_root
    raise ValueError(
        "bundled marketplace does not contain the supplied computer-use plugin"
    )


def prepare_codex_home(codex_home: Path, force: bool) -> None:
    marker = codex_home / MARKER_NAME
    if codex_home.exists():
        if not force:
            raise ValueError(f"codex home already exists: {codex_home}")
        if not marker.is_file():
            raise ValueError(f"refusing to overwrite unmarked directory: {codex_home}")
        shutil.rmtree(codex_home)
    codex_home.mkdir(parents=True, mode=0o700)
    codex_home.chmod(0o700)
    marker.write_text("generated by promptfoo computer-use example\n")


def write_config(
    codex_home: Path, marketplace_name: str, marketplace_root: Path
) -> Path:
    if not SAFE_NAME_RE.fullmatch(marketplace_name):
        raise ValueError(
            "marketplace name may contain only letters, numbers, dots, underscores, and dashes"
        )

    config_path = codex_home / "config.toml"
    config_path.write_text(
        "[features]\n"
        "plugins = true\n\n"
        f'[plugins."{PLUGIN_NAME}@{marketplace_name}"]\n'
        "enabled = true\n\n"
        f'[marketplaces."{marketplace_name}"]\n'
        'source_type = "local"\n'
        f"source = {json.dumps(str(marketplace_root))}\n"
    )
    return config_path


def main() -> None:
    args = parse_args()
    plugin_dir = args.plugin_dir.expanduser().resolve()
    codex_home = args.codex_home.expanduser().resolve()

    launcher = resolve_launcher(plugin_dir)
    marketplace_name, marketplace_root = resolve_marketplace(plugin_dir)
    prepare_codex_home(codex_home, args.force)
    config = write_config(codex_home, marketplace_name, marketplace_root)

    print(f"staged Codex home: {codex_home}")
    print(f"marketplace: {marketplace_root}")
    print(f"config: {config}")
    print(f"launcher: {launcher}")
    print("auth: not copied")


if __name__ == "__main__":
    main()
