export const ADVANCED_REDTEAM_AGENT_PROVIDER_ID = 'promptfoo:redteam:simba';
export const ADVANCED_REDTEAM_AGENT_STRATEGY_ID = 'simba';
export const ADVANCED_REDTEAM_AGENT_DISPLAY_NAME = 'Advanced Redteam Agent';
export const ADVANCED_REDTEAM_AGENT_PROMPT_LABEL = `${ADVANCED_REDTEAM_AGENT_DISPLAY_NAME} Attack`;
export const ADVANCED_REDTEAM_AGENT_RESULT_PROMPT_LABEL = ADVANCED_REDTEAM_AGENT_DISPLAY_NAME;
export const ADVANCED_REDTEAM_AGENT_METRIC_SUFFIX = 'Advanced Redteam Agent';
export const ADVANCED_REDTEAM_AGENT_LOGGER_PREFIX = `[${ADVANCED_REDTEAM_AGENT_DISPLAY_NAME}]`;
