/**
 * XML tool call parsing utilities for MCP provider integration.
 * These functions convert XML-formatted tool calls (generated by LLMs) to JSON.
 */

/**
 * Decode XML entities to their character equivalents.
 * Note: &amp; must be decoded last to prevent double-decoding issues
 * (e.g., &amp;quot; should become &quot;, not ")
 */
export function decodeXmlEntities(text: string): string {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/**
 * Parse a value with an explicit type attribute for MCP XML format.
 */
export function parseTypedValue(value: string, type?: string): string | number | boolean | null {
  const decoded = decodeXmlEntities(value);
  const trimmed = decoded.trim();

  switch (type) {
    case 'number':
      return Number(trimmed);
    case 'boolean':
      return trimmed === 'true';
    case 'null':
      return null;
    default:
      return decoded;
  }
}

/**
 * Parse XML tool call format into JSON structure.
 * Returns null if not valid XML tool call format.
 */
export function parseXmlToolCall(
  xml: string,
): { tool: string; args: Record<string, string | number | boolean | null> } | null {
  if (!xml.includes('<tool-call>') || !xml.includes('</tool-call>')) {
    return null;
  }

  const toolMatch = xml.match(/<tool>([^<]+)<\/tool>/);
  if (!toolMatch) {
    return null;
  }
  const tool = toolMatch[1].trim();

  const argsMatch = xml.match(/<args>([\s\S]*?)<\/args>/);
  const args: Record<string, string | number | boolean | null> = {};

  if (argsMatch) {
    const argsContent = argsMatch[1];
    const argPattern = /<([a-zA-Z_][a-zA-Z0-9_]*)(?:\s+type="([^"]*)")?>([\s\S]*?)<\/\1>/g;
    let match;
    while ((match = argPattern.exec(argsContent)) !== null) {
      const paramName = match[1];
      const paramType = match[2];
      const paramValue = match[3].trim();
      args[paramName] = parseTypedValue(paramValue, paramType);
    }
  }

  return { tool, args };
}
