import type { Config } from 'jest';

const config: Config = {
  collectCoverage: false,
  coverageDirectory: '.coverage',
  coverageProvider: 'v8',
  extensionsToTreatAsEsm: ['.ts'],
  modulePathIgnorePatterns: ['<rootDir>/dist', '<rootDir>/examples', '<rootDir>/node_modules'],
  setupFiles: ['<rootDir>/.jest/setEnvVars.js'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testEnvironmentOptions: {
    globalsCleanup: 'soft',
  },
  testPathIgnorePatterns: [
    '.*\\.integration\\.test\\.ts$',
    '<rootDir>/dist',
    '<rootDir>/examples',
    '<rootDir>/node_modules',
    '<rootDir>/src/app',
    // These tests are now run with Vitest (npm run test:vitest)
    '<rootDir>/test/assertions',
    '<rootDir>/test/codeScans',
    '<rootDir>/test/matchers',
    '<rootDir>/test/database',
    '<rootDir>/test/site',
    '<rootDir>/test/testCase',
    '<rootDir>/test/validators',
    '<rootDir>/test/utils',
    '<rootDir>/test/models',
    '<rootDir>/test/app',
    '<rootDir>/test/globalConfig',
    '<rootDir>/test/integrations',
    '<rootDir>/test/external',
    '<rootDir>/test/progress',
    '<rootDir>/test/types',
    '<rootDir>/test/providers/bedrock/index.test.ts',
    '<rootDir>/test/providers/azure',
    '<rootDir>/test/providers/azure.test.ts',
    '<rootDir>/test/providers/anthropic',
    '<rootDir>/test/providers/openai/responses.test.ts',
    '<rootDir>/test/providers/openai/util.test.ts',
    '<rootDir>/test/providers/xai',
    '<rootDir>/test/providers/adaline.gateway.test.ts',
    '<rootDir>/test/providers/ai21.test.ts',
    '<rootDir>/test/providers/alibaba.test.ts',
    '<rootDir>/test/providers/fal.test.ts',
    '<rootDir>/test/providers/packageParser.test.ts',
    '<rootDir>/test/providers/scriptCompletion.test.ts',
    '<rootDir>/test/providers/togetherai.test.ts',
    '<rootDir>/test/providers/deepseek.test.ts',
    '<rootDir>/test/providers/ollama.test.ts',
    '<rootDir>/test/providers/truefoundry.test.ts',
    '<rootDir>/test/providers/pythonCompletion.test.ts',
    '<rootDir>/test/providers/pythonCompletion.fileRef.test.ts',
    '<rootDir>/test/providers/pythonCompletion.unicode.test.ts',
    '<rootDir>/test/providers/mcp',
    '<rootDir>/test/providers/functionCallbackUtils.test.ts',
    '<rootDir>/test/providers/claude-agent-sdk.test.ts',
    '<rootDir>/test/providers/cloudflare-ai.test.ts',
    '<rootDir>/test/providers/browser.test.ts',
    '<rootDir>/test/providers/groq',
    '<rootDir>/test/providers/hyperbolic',
    '<rootDir>/test/providers/hyperbolic.test.ts',
    '<rootDir>/test/providers/openai/chat.test.ts',
    '<rootDir>/test/providers/openai/image.test.ts',
    '<rootDir>/test/providers/openai/transcription.test.ts',
    '<rootDir>/test/prompts',
    '<rootDir>/test/python',
    '<rootDir>/test/commands/generate',
    '<rootDir>/test/providers/http.test.ts',
    '<rootDir>/test/logger.test.ts',
    '<rootDir>/test/cache.test.ts',
    '<rootDir>/test/account.test.ts',
    '<rootDir>/test/constants.test.ts',
    '<rootDir>/test/monkeyPatchFetch.test.ts',
    '<rootDir>/test/config-schema.test.ts',
    '<rootDir>/test/envars.test.ts',
    '<rootDir>/test/feedback.test.ts',
    '<rootDir>/test/checkNodeVersion.test.ts',
    '<rootDir>/test/csv.test.ts',
    '<rootDir>/test/index.test.ts',
    '<rootDir>/test/googleSheets.test.ts',
    '<rootDir>/test/microsoftSharepoint.test.ts',
    '<rootDir>/test/providers.slack.test.ts',
    '<rootDir>/test/rateLimit.test.ts',
    '<rootDir>/test/share.test.ts',
    '<rootDir>/test/updates.test.ts',
    '<rootDir>/test/tracing',
    '<rootDir>/test/util',
    '<rootDir>/test/providers/rubyCompletion.test.ts',
    '<rootDir>/test/providers/websocket.test.ts',
    '<rootDir>/test/providers/llamaApi.test.ts',
    '<rootDir>/test/providers/shared.test.ts',
    '<rootDir>/test/providers/snowflake.test.ts',
    '<rootDir>/test/providers/webhook.test.ts',
    '<rootDir>/test/providers/cometapi.test.ts',
    '<rootDir>/test/providers/llama.test.ts',
    '<rootDir>/test/providers/promptfooModel.test.ts',
    '<rootDir>/test/providers/helicone.test.ts',
    '<rootDir>/test/providers/aimlapi.test.ts',
    '<rootDir>/test/providers/scriptBasedProvider.test.ts',
    '<rootDir>/test/providers/replicate-image.test.ts',
    '<rootDir>/test/providers/openai/defaults.test.ts',
    '<rootDir>/test/providers/openai/embedding.test.ts',
    '<rootDir>/test/providers/github/defaults.test.ts',
    '<rootDir>/test/providers/github/index.test.ts',
    '<rootDir>/test/providers/github/integration.test.ts',
    '<rootDir>/test/providers/google/util.test.ts',
    '<rootDir>/test/providers/google/vertex.test.ts',
  ],
  transform: {
    '^.+\\.m?[tj]sx?$': '@swc/jest',
  },
  // Transform ESM-only packages in node_modules
  // Use a permissive pattern that transforms most ESM packages
  transformIgnorePatterns: [
    'node_modules/(?!(@sindresorhus|execa|strip-final-newline|npm-run-path|path-key|onetime|mimic-fn|human-signals|is-stream|merge-stream|get-stream|is-plain-obj|yocto-queue|figures|is-unicode-supported)/)',
  ],
  // Use a more conservative worker pool configuration to prevent segmentation faults
  maxWorkers: '50%',
  workerIdleMemoryLimit: '1GB',
};

export default config;
