import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Gradual migration from Jest - add directories here as they're migrated
    include: [
      'test/assertions/**/*.test.ts',
      'test/codeScans/**/*.test.ts',
      'test/matchers/**/*.test.ts',
      'test/database/**/*.test.ts',
      'test/site/**/*.test.ts',
      'test/testCase/**/*.test.ts',
      'test/validators/**/*.test.ts',
      'test/utils/**/*.test.ts',
      'test/models/**/*.test.ts',
      'test/app/**/*.test.ts',
      'test/globalConfig/**/*.test.ts',
      'test/integrations/**/*.test.ts',
      'test/external/**/*.test.ts',
      'test/progress/**/*.test.ts',
      'test/types/**/*.test.ts',
      'test/providers/bedrock/index.test.ts',
      'test/providers/azure/**/*.test.ts',
      'test/providers/azure.test.ts',
      'test/providers/anthropic/**/*.test.ts',
      'test/providers/openai/{responses,util}.test.ts',
      'test/providers/xai/**/*.test.ts',
      'test/providers/ollama.test.ts',
      'test/providers/truefoundry.test.ts',
      'test/providers/pythonCompletion*.test.ts',
      'test/providers/mcp/**/*.test.ts',
      'test/providers/functionCallbackUtils.test.ts',
      'test/providers/claude-agent-sdk.test.ts',
      'test/providers/cloudflare-ai.test.ts',
      'test/providers/browser.test.ts',
      'test/providers/groq/**/*.test.ts',
      'test/providers/hyperbolic/**/*.test.ts',
      'test/providers/hyperbolic.test.ts',
      'test/providers/openai/{chat,image,transcription}.test.ts',
      'test/prompts/**/*.test.ts',
      'test/python/**/*.test.ts',
      'test/commands/generate/**/*.test.ts',
      'test/providers/http.test.ts',
      'test/providers/{adaline.gateway,ai21,alibaba,fal,packageParser,scriptCompletion,togetherai,deepseek}.test.ts',
      'test/logger.test.ts',
      'test/cache.test.ts',
      'test/account.test.ts',
      'test/constants.test.ts',
      'test/monkeyPatchFetch.test.ts',
      'test/config-schema.test.ts',
      'test/envars.test.ts',
      'test/feedback.test.ts',
      'test/checkNodeVersion.test.ts',
      'test/csv.test.ts',
      'test/index.test.ts',
      'test/googleSheets.test.ts',
      'test/microsoftSharepoint.test.ts',
      'test/providers.slack.test.ts',
      'test/rateLimit.test.ts',
      'test/share.test.ts',
      'test/updates.test.ts',
      'test/tracing/**/*.test.ts',
      'test/util/**/*.test.ts',
      'test/providers/rubyCompletion.test.ts',
      'test/providers/websocket.test.ts',
      'test/providers/llamaApi.test.ts',
      'test/providers/shared.test.ts',
      'test/providers/snowflake.test.ts',
      'test/providers/webhook.test.ts',
      'test/providers/cometapi.test.ts',
      'test/providers/llama.test.ts',
      'test/providers/promptfooModel.test.ts',
      'test/providers/helicone.test.ts',
      'test/providers/aimlapi.test.ts',
      'test/providers/scriptBasedProvider.test.ts',
      'test/providers/replicate-image.test.ts',
      'test/providers/openai/defaults.test.ts',
      'test/providers/openai/embedding.test.ts',
      'test/providers/github/defaults.test.ts',
      'test/providers/github/index.test.ts',
      'test/providers/github/integration.test.ts',
      'test/providers/google/{util,vertex}.test.ts',
    ],
    // Exclude integration tests
    exclude: ['**/*.integration.test.ts', '**/node_modules/**'],
    // Use node environment (not jsdom) for backend tests
    environment: 'node',
    // Enable globals so we don't need to import describe/it/expect everywhere
    globals: true,
    // Setup files
    setupFiles: ['./vitest.setup.ts'],
    // Root directory
    root: '.',
    // Transform settings for ESM packages
    deps: {
      interopDefault: true,
    },
  },
});
