import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Gradual migration from Jest - add directories here as they're migrated
    include: [
      'test/assertions/**/*.test.ts',
      'test/codeScans/**/*.test.ts',
      'test/matchers/**/*.test.ts',
      'test/database/**/*.test.ts',
      'test/site/**/*.test.ts',
      'test/testCase/**/*.test.ts',
      'test/validators/**/*.test.ts',
      'test/utils/**/*.test.ts',
      'test/models/**/*.test.ts',
      'test/app/**/*.test.ts',
      'test/globalConfig/**/*.test.ts',
      'test/integrations/**/*.test.ts',
      'test/external/**/*.test.ts',
      'test/progress/**/*.test.ts',
      'test/types/**/*.test.ts',
      'test/providers/**/*.test.ts',
      'test/prompts/**/*.test.ts',
      'test/python/**/*.test.ts',
      'test/commands/**/*.test.ts',
      'test/server/**/*.test.ts',
      'test/tracing/**/*.test.ts',
      'test/util/**/*.test.ts',
      'test/redteam/**/*.test.ts',
      'test/logger.test.ts',
      'test/cache.test.ts',
      'test/account.test.ts',
      'test/constants.test.ts',
      'test/monkeyPatchFetch.test.ts',
      'test/config-schema.test.ts',
      'test/envars.test.ts',
      'test/feedback.test.ts',
      'test/checkNodeVersion.test.ts',
      'test/csv.test.ts',
      'test/index.test.ts',
      'test/googleSheets.test.ts',
      'test/microsoftSharepoint.test.ts',
      'test/providers.slack.test.ts',
      'test/rateLimit.test.ts',
      'test/share.test.ts',
      'test/updates.test.ts',
      'test/table.test.ts',
      'test/globalConfig.test.ts',
      'test/esm.test.ts',
      'test/onboarding.test.ts',
      'test/sagemaker.test.ts',
      'test/main.test.ts',
      'test/guardrails.test.ts',
      'test/evaluatorHelpers.test.ts',
      'test/evaluatorHelpers-skiprender.test.ts',
      'test/evaluator.progress.test.ts',
      'test/evaluatorHelpers.langfuse.test.ts',
      'test/evaluator.integration.transforms.test.ts',
      'test/code-scan-action/auth.test.ts',
      'test/code-scan-action/config.test.ts',
      'test/code-scan-action/github.test.ts',
      'test/integration/function-provider-grading.test.ts',
      'test/integration/envPath.test.ts',
      'test/evaluator/trace-integration.test.ts',
      'test/scripts/**/*.test.ts',
      'test/fetch.test.ts',
    ],
    // Exclude integration tests
    exclude: ['**/*.integration.test.ts', '**/node_modules/**'],
    // Use node environment (not jsdom) for backend tests
    environment: 'node',
    // Enable globals so we don't need to import describe/it/expect everywhere
    globals: true,
    // Setup files
    setupFiles: ['./vitest.setup.ts'],
    // Root directory
    root: '.',
    // Transform settings for ESM packages
    deps: {
      interopDefault: true,
    },
  },
});
