// Maps old example names to their new names after the category prefix reorganization.
// This ensures `npx promptfoo init --example <old-name>` still works.
export const EXAMPLE_ALIASES: Record<string, string> = {
  'agentic-sdk-comparison': 'compare-agentic-sdks',
  'amazon-bedrock': 'amazon-bedrock/models',
  'amazon-sagemaker': 'provider-amazon-sagemaker',
  'assertion-scoring-override': 'eval-assertion-scoring-override',
  'assertions-generate': 'eval-assertions-generate',
  'bedrock-agents': 'amazon-bedrock/agents',
  'bedrock-video': 'amazon-bedrock/video',
  'bert-score': 'eval-bert-score',
  'browser-existing-session': 'integration-browser/existing-session',
  cerebras: 'provider-cerebras',
  'claude-vs-gpt': 'compare-claude-vs-gpt',
  'claude-vs-gpt-image': 'compare-claude-vs-gpt-image',
  'cloudflare-ai': 'provider-cloudflare/ai',
  'cloudflare-gateway': 'provider-cloudflare/gateway',
  cohere: 'provider-cohere',
  'cohere-benchmark': 'provider-cohere-benchmark',
  cometapi: 'provider-cometapi',
  'conversation-relevance': 'eval-conversation-relevance',
  crewai: 'integration-crewai',
  'csv-metadata': 'config-csv-metadata',
  'custom-grader-csv': 'eval-custom-grader-csv',
  'custom-grading-prompt': 'eval-custom-grading-prompt',
  'custom-prompt-function': 'config-custom-prompt-function',
  'custom-provider': 'provider-custom/basic',
  'custom-provider-embeddings': 'provider-custom/embeddings',
  'custom-provider-mjs': 'provider-custom/mjs',
  'custom-provider-typescript': 'provider-custom/typescript',
  cyberseceval: 'redteam-cyberseceval',
  databricks: 'provider-databricks',
  'dbrx-benchmark': 'provider-databricks',
  'deepseek-r1-vs-openai-o1': 'compare-deepseek-r1-vs-openai-o1',
  docker: 'integration-docker/basic',
  'docker-code-generation-sandbox': 'integration-docker/code-generation-sandbox',
  donotanswer: 'redteam-donotanswer',
  'dynamic-var': 'config-dynamic-var',
  'e2b-code-eval': 'integration-e2b',
  'elevenlabs-agents': 'provider-elevenlabs/agents',
  'elevenlabs-alignment': 'provider-elevenlabs/alignment',
  'elevenlabs-isolation': 'provider-elevenlabs/isolation',
  'elevenlabs-stt': 'provider-elevenlabs/stt',
  'elevenlabs-tts': 'provider-elevenlabs/tts',
  'elevenlabs-tts-advanced': 'provider-elevenlabs/tts-advanced',
  'errors-vs-failures': 'eval-errors-vs-failures',
  'executable-prompts': 'config-executable-prompts',
  'extension-api': 'config-extension-api',
  'external-defaulttest': 'config-external-defaulttest',
  'external-provider-config': 'config-external-provider-config',
  'f-score': 'eval-f-score',
  'fal-image-generation': 'provider-fal',
  'function-tools-callback': 'eval-function-tools-callback',
  'g-eval': 'eval-g-eval',
  'github-action': 'integration-github-action',
  'github-models': 'provider-github-models',
  'golang-provider': 'provider-golang',
  'google-adk-example': 'integration-google-adk',
  'google-sheets': 'integration-google-sheets',
  'gpt-4o-temperature-comparison': 'compare-gpt-temperature',
  'gpt-4o-vs-4o-mini': 'compare-gpt-4o-vs-4o-mini',
  'gpt-vs-claude-vs-gemini': 'compare-gpt-vs-claude-vs-gemini',
  'grok-4-political-bias': 'redteam-grok-4-political-bias',
  groq: 'provider-groq',
  harmbench: 'redteam-harmbench',
  'headless-browser': 'integration-browser/headless',
  helicone: 'integration-helicone',
  'http-provider': 'provider-http/basic',
  'http-provider-auth-signature': 'provider-http/auth-signature',
  'http-provider-auth-signature-jks': 'provider-http/auth-signature-jks',
  'http-provider-auth-signature-pfx': 'provider-http/auth-signature-pfx',
  'http-provider-streaming': 'provider-http/streaming',
  'http-provider-tls': 'provider-http/tls',
  'huggingface-chat': 'huggingface/chat',
  'huggingface-dataset': 'huggingface/dataset',
  'huggingface-dataset-factuality': 'huggingface/dataset-factuality',
  'huggingface-hate-speech-detection': 'huggingface/hate-speech-detection',
  'huggingface-hle': 'huggingface/hle',
  'huggingface-inference-endpoint': 'huggingface/inference-endpoint',
  'huggingface-pii': 'huggingface/pii',
  'huggingface-similarity': 'huggingface/similarity',
  hyperbolic: 'provider-hyperbolic',
  'image-classification': 'eval-image-classification',
  'javascript-assert-external': 'eval-javascript-assert-external',
  'javascript-test-cases': 'config-javascript-test-cases',
  'jest-integration': 'integration-jest',
  'js-config': 'config-js',
  'json-output': 'eval-json-output',
  'jsonl-test-cases': 'config-jsonl-test-cases',
  'langchain-python': 'integration-langchain',
  'langfuse-labels': 'integration-langfuse',
  langgraph: 'integration-langgraph',
  litellm: 'provider-litellm',
  'llama-cpp': 'provider-llama-cpp',
  'llama-gpt-comparison': 'compare-llama-vs-gpt',
  'lm-studio': 'provider-lm-studio',
  'max-score-selection': 'eval-max-score-selection',
  'mistral-llama-comparison': 'compare-mistral-vs-llama',
  'model-armor': 'provider-model-armor',
  'modelslab-image-generation': 'provider-modelslab',
  moderation: 'eval-moderation',
  'multiple-configs': 'config-multiple-configs',
  'multiple-translations': 'config-multiple-translations',
  'multiple-turn-conversation': 'config-multi-turn',
  multishot: 'config-multishot',
  'named-metrics': 'eval-named-metrics',
  'node-module-package': 'config-node-module-package',
  'node-package': 'config-node-package',
  'node-package-typescript': 'config-node-package-typescript',
  nscale: 'provider-nscale',
  'nunjucks-custom-filters': 'config-nunjucks-custom-filters',
  'openai-gpt-5-vs-gpt-5-mini-mmlu': 'compare-gpt-5-vs-gpt-5-mini-mmlu',
  'openai-model-comparison': 'compare-openai-models',
  openclaw: 'provider-openclaw',
  'opencode-sdk': 'provider-opencode-sdk/basic',
  'opencode-sdk/basic': 'provider-opencode-sdk/basic',
  'open-source-comparison': 'compare-open-source-models',
  'provider-opencode-sdk': 'provider-opencode-sdk/basic',
  'opentelemetry-tracing': 'integration-opentelemetry/javascript',
  'opentelemetry-tracing-python': 'integration-opentelemetry/python',
  'otel-tracing': 'integration-opentelemetry/built-in',
  'pdf-files': 'config-pdf-files',
  'pdf-variables': 'config-pdf-variables',
  'perplexity.ai-example': 'provider-perplexity',
  'phi-vs-llama': 'compare-phi-vs-llama',
  'portkey-test': 'provider-portkey',
  'prompt-labels': 'config-prompt-labels',
  'prompts-per-model': 'config-prompts-per-model',
  'pydantic-ai': 'integration-pydantic-ai',
  'python-assert': 'eval-python-assert',
  'python-provider': 'provider-python',
  'python-test-cases': 'config-python-test-cases',
  quiverai: 'provider-quiverai',
  'rag-eval': 'eval-rag',
  'rag-full': 'eval-rag-full',
  'replicate-comprehensive': 'provider-replicate/comprehensive',
  'replicate-image-generation': 'provider-replicate/image-generation',
  'replicate-lifeboat': 'provider-replicate/lifeboat',
  'replicate-llama-guard-moderation': 'provider-replicate/llama-guard-moderation',
  'replicate-llama4-scout': 'provider-replicate/llama4-scout',
  'replicate-quickstart': 'provider-replicate/quickstart',
  'result-hooks': 'config-result-hooks',
  'retry-testing': 'config-retry-testing',
  'ruby-provider': 'provider-ruby',
  'search-rubric': 'eval-search-rubric',
  'select-best-example': 'eval-select-best',
  'self-grading': 'eval-self-grading',
  'separate-test-configs': 'config-separate-test-configs',
  'sharepoint-integration': 'integration-sharepoint',
  'slack-human-feedback': 'integration-slack',
  'sql-validation': 'eval-sql-validation',
  'standalone-assertions': 'eval-standalone-assertions',
  'stateful-session-management': 'config-stateful-session-management',
  'store-and-reuse-outputs': 'config-store-and-reuse-outputs',
  'strands-agents': 'integration-strands-agents',
  'structured-outputs-config': 'config-structured-outputs',
  summarization: 'eval-summarization',
  'tau-simulated-user': 'integration-tau',
  'test-markdown': 'eval-markdown-rendering',
  'tests-per-prompt': 'config-tests-per-prompt',
  'tests-per-provider': 'config-tests-per-provider',
  'tool-use': 'eval-tool-use',
  'transform-file': 'config-transform-file',
  'transformers-local': 'provider-transformers-local',
  truefoundry: 'provider-truefoundry',
  'ts-config': 'config-ts',
  'vars-referencing-vars': 'config-vars-referencing-vars',
  'vercel-ai-gateway': 'integration-vercel/ai-gateway',
  'vercel-ai-sdk': 'integration-vercel/ai-sdk',
  'voyage-embeddings': 'provider-voyage-embeddings',
  watsonx: 'provider-watsonx',
  websockets: 'config-websockets/basic',
  'websockets-streaming': 'config-websockets/streaming',
  'xai-video': 'xai/video',
  'xai-voice': 'xai/voice',
  xai: 'xai/chat',
  xstest: 'redteam-xstest',
};

// Aliases where the old example was removed and we route to the closest maintained alternative.
export const EXAMPLE_REPLACEMENTS: Record<string, string> = {
  'dbrx-benchmark': 'dbrx-benchmark was removed because DBRX is no longer available.',
};

// Examples that were intentionally removed from current examples/
// but can still be downloaded from a legacy git ref for backwards compatibility.
export const REMOVED_EXAMPLES: Record<
  string,
  {
    legacyRef: string;
    reason: string;
  }
> = {
  'assistant-cli': {
    legacyRef: '0.120.26',
    reason: 'assistant-cli was removed because it is redundant with newer examples.',
  },
  'colab-notebook': {
    legacyRef: '0.120.26',
    reason: 'colab-notebook was removed because it no longer works with current dependencies.',
  },
  'elevenlabs-supporting-apis': {
    legacyRef: '0.120.26',
    reason: 'elevenlabs-supporting-apis was removed because the example is deprecated.',
  },
  'gemma-vs-llama': {
    legacyRef: '0.120.26',
    reason: 'gemma-vs-llama was removed because the underlying model is no longer available.',
  },
  'gemma-vs-mistral': {
    legacyRef: '0.120.26',
    reason: 'gemma-vs-mistral was removed because the underlying model is no longer available.',
  },
};
