# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
# This configuration compares LLM output of 2 prompts x 2 GPT models across 3 test cases.
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'My first eval'

prompts:
  - 'Write a tweet about {{topic}}'

providers:
  - id: openai:chat:gpt-5.4-mini
  - id: openai:chat:gpt-5.5

tests:
  - vars:
      topic: new york city

  - vars:
      topic: mexico
