/**
 * Post-process the typedoc-plugin-markdown output for the Node.js API reference.
 *
 * The generated tree is used as-is on the docs site, but TypeDoc's Markdown
 * output needs a small Docusaurus cleanup pass:
 * - the entry README has no useful frontmatter by default
 * - child pages include redundant breadcrumb scaffolding before their first H1
 * - Docusaurus renders its own page title unless we explicitly hide it, which
 *   leaves generated pages with duplicate H1s
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const REFERENCE_DIR = path.resolve('site/docs/api/node/reference');
const README_PATH = path.join(REFERENCE_DIR, 'README.md');
const FRONTMATTER = `---
title: Node.js API - Reference index
sidebar_label: Reference index
description: Index of the curated Node.js API surface generated by TypeDoc.
---

`;
const README_GUIDANCE = `## How to use this reference

Start with the [Node.js package guide](../../../usage/node-package.md) when you
need workflows and examples. Use this generated reference when you need the
exact public symbols, signatures, import form, and field-level contracts.

The pages below document the curated package surface exported from \`promptfoo\`,
not every internal compatibility type that exists in the runtime build.

`;
function buildGeneratedPageFrontmatter(title: string, description: string) {
  return `---
title: ${JSON.stringify(title)}
description: ${JSON.stringify(description)}
---

`;
}

function stripMarkdown(value: string) {
  return value
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[`_*]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function getDescription(markdown: string) {
  const paragraphs = markdown
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);

  for (const paragraph of paragraphs) {
    if (
      paragraph.startsWith('>') ||
      paragraph.startsWith('Defined in:') ||
      paragraph.startsWith('## ') ||
      paragraph.startsWith('```') ||
      paragraph.startsWith('- ')
    ) {
      continue;
    }

    const description = stripMarkdown(paragraph);
    return description.match(/^.*?[.!?](?:\s|$)/)?.[0].trim() ?? description;
  }

  return 'Generated Node.js API reference page.';
}

function getSymbolName(title: string) {
  return title
    .replace(/^(Function|Interface|Type Alias|Variable): /, '')
    .replace(/\\</g, '<')
    .replace(/\\>/g, '>')
    .replace(/<.*$/, '')
    .replace(/\(\)$/, '');
}

function buildImportSection(entryPath: string, title: string) {
  const relativePath = path.relative(REFERENCE_DIR, entryPath);
  const symbolName = getSymbolName(title);

  if (relativePath === path.join('promptfoo', 'namespaces', 'cache', 'README.md')) {
    return `## Import

\`\`\`ts
import { cache } from 'promptfoo';
\`\`\`

`;
  }

  if (relativePath.startsWith(path.join('promptfoo', 'namespaces', 'cache'))) {
    if (relativePath.includes(`${path.sep}type-aliases${path.sep}`)) {
      return `## Import

\`\`\`ts
import { cache } from 'promptfoo';

type Result = cache.${symbolName}<unknown>;
\`\`\`

`;
    }

    return `## Import

\`\`\`ts
import { cache } from 'promptfoo';
\`\`\`

`;
  }

  if (
    relativePath.startsWith(`interfaces${path.sep}`) ||
    relativePath.startsWith(`type-aliases${path.sep}`)
  ) {
    return `## Import

\`\`\`ts
import type { ${symbolName} } from 'promptfoo';
\`\`\`

`;
  }

  if (
    relativePath.startsWith(`functions${path.sep}`) ||
    relativePath.startsWith(`variables${path.sep}`)
  ) {
    return `## Import

\`\`\`ts
import { ${symbolName} } from 'promptfoo';
\`\`\`

`;
  }

  return '';
}

function rewriteReadme() {
  if (!fs.existsSync(README_PATH)) {
    throw new Error(`Generated reference README not found at ${README_PATH}`);
  }
  const original = fs.readFileSync(README_PATH, 'utf8');
  if (original.startsWith('---\n')) {
    return;
  }
  const withoutBreadcrumb = original.replace(/^\*\*promptfoo\*\*\n\n(?:\*\*\*|---)\n\n/, '');
  const withFixedTitle = withoutBreadcrumb.replace(/^# promptfoo\n/, '# Reference index\n');
  const withGuidance = withFixedTitle.replace(/(\n## Namespaces\n)/, `\n${README_GUIDANCE}$1`);
  fs.writeFileSync(README_PATH, FRONTMATTER + withGuidance, 'utf8');
}

function rewriteGeneratedPages() {
  const pending = [REFERENCE_DIR];

  while (pending.length > 0) {
    const currentDir = pending.pop();
    if (!currentDir) {
      continue;
    }

    for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
      const entryPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        pending.push(entryPath);
        continue;
      }
      if (!entry.isFile() || path.extname(entry.name) !== '.md' || entryPath === README_PATH) {
        continue;
      }

      const original = fs.readFileSync(entryPath, 'utf8');
      const firstHeading = original.match(/^# (.+)$/m);
      if (!firstHeading?.[1] || firstHeading.index === undefined) {
        continue;
      }

      const title = firstHeading[1];
      const afterHeading = original
        .slice(firstHeading.index + firstHeading[0].length)
        .replace(/^\n+/, '');
      const importSection = buildImportSection(entryPath, title);
      const description = getDescription(afterHeading);
      fs.writeFileSync(
        entryPath,
        buildGeneratedPageFrontmatter(title, description) + importSection + afterHeading,
        'utf8',
      );
    }
  }
}

rewriteReadme();
rewriteGeneratedPages();
