/**
 * Curated Node.js API reference surface.
 *
 * This file is used only by TypeDoc. Every export here is also available from
 * the root `promptfoo` package entrypoint, but the runtime package exports more
 * compatibility types and helpers than we want to present as first-class docs.
 *
 * @packageDocumentation
 */

export {
  assertions,
  cache,
  evaluate,
  generateTable,
  isTransformFunction,
  loadApiProvider,
  loadApiProviders,
} from '../src/index';

export type {
  ApiProvider,
  Assertion,
  AssertionInput,
  AssertionOrSet,
  AssertionSet,
  AssertionTestContext,
  AssertionTokenUsage,
  AssertionValueFunction,
  AssertionValueFunctionContext,
  AtomicTestCase,
  AudioOutput,
  BlobRef,
  CallApiContextParams,
  CallApiFunction,
  CallApiOptionsParams,
  ChatMessage,
  CompletedPrompt,
  CompletionTokenDetails,
  ConversationMessage,
  EnvOverrides,
  EvaluateOptions,
  EvaluateProgressCallback,
  EvaluateTable,
  EvaluateTableHead,
  EvaluateTableOutput,
  EvaluateTableRow,
  EvaluateTestSuite,
  GradingResult,
  GuardrailResponse,
  ImageOutput,
  LoadApiProviderContext,
  LoadApiProvidersOptions,
  ModerationMatchOptions,
  PluginConfig,
  PluginGraderExample,
  Prompt,
  PromptConfig,
  PromptContent,
  PromptFunction,
  PromptFunctionResult,
  PromptMetrics,
  ProviderClassificationResponse,
  ProviderConfig,
  ProviderEmbeddingResponse,
  ProviderFunction,
  ProviderOptions,
  ProviderResponse,
  ProviderSimilarityResponse,
  ProvidersConfig,
  RunAssertionOptions,
  RunAssertionsOptions,
  ScoringFunction,
  StrategyConfig,
  TestCase,
  TestCaseMetadata,
  TestCaseOptions,
  TokenUsage,
  TransformContext,
  TransformFunction,
  TransformPrompt,
  VideoOutput,
} from '../src/index';
