/**
 * Post-process the typedoc-plugin-markdown output for the Node.js API reference.
 *
 * The generated tree is used as-is on the docs site, but the entry README has no
 * Docusaurus frontmatter (no title, no sidebar label), which makes it render as
 * "promptfoo" in the sidebar and breadcrumb. We rewrite the README to include
 * frontmatter and a more useful page title.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const REFERENCE_DIR = path.resolve('site/docs/api/node/reference');
const README_PATH = path.join(REFERENCE_DIR, 'README.md');
const FRONTMATTER = `---
title: Node.js API — Reference index
sidebar_label: Reference index
description: Index of the curated Node.js API surface generated by TypeDoc.
---

`;

function rewriteReadme() {
  if (!fs.existsSync(README_PATH)) {
    throw new Error(`Generated reference README not found at ${README_PATH}`);
  }
  const original = fs.readFileSync(README_PATH, 'utf8');
  if (original.startsWith('---\n')) {
    return;
  }
  const withoutBreadcrumb = original.replace(/^\*\*promptfoo\*\*\n\n(?:\*\*\*|---)\n\n/, '');
  const withFixedTitle = withoutBreadcrumb.replace(/^# promptfoo\n/, '# Reference index\n');
  fs.writeFileSync(README_PATH, FRONTMATTER + withFixedTitle, 'utf8');
}

rewriteReadme();
