/**
 * Post-process the typedoc-plugin-markdown output for the Node.js API reference.
 *
 * The generated tree is used as-is on the docs site, but TypeDoc's Markdown
 * output needs a small Docusaurus cleanup pass:
 * - the entry README has no useful frontmatter by default
 * - child pages include redundant breadcrumb scaffolding before their first H1
 * - Docusaurus renders its own page title unless we explicitly hide it, which
 *   leaves generated pages with duplicate H1s
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const REFERENCE_DIR = path.resolve('site/docs/api/node/reference');
const README_PATH = path.join(REFERENCE_DIR, 'README.md');
const FRONTMATTER = `---
title: Node.js API - Reference index
sidebar_label: Reference index
description: Index of the curated Node.js API surface generated by TypeDoc.
---

`;
function buildGeneratedPageFrontmatter(title: string) {
  return `---
title: ${JSON.stringify(title)}
---

`;
}

function rewriteReadme() {
  if (!fs.existsSync(README_PATH)) {
    throw new Error(`Generated reference README not found at ${README_PATH}`);
  }
  const original = fs.readFileSync(README_PATH, 'utf8');
  if (original.startsWith('---\n')) {
    return;
  }
  const withoutBreadcrumb = original.replace(/^\*\*promptfoo\*\*\n\n(?:\*\*\*|---)\n\n/, '');
  const withFixedTitle = withoutBreadcrumb.replace(/^# promptfoo\n/, '# Reference index\n');
  fs.writeFileSync(README_PATH, FRONTMATTER + withFixedTitle, 'utf8');
}

function rewriteGeneratedPages() {
  const pending = [REFERENCE_DIR];

  while (pending.length > 0) {
    const currentDir = pending.pop();
    if (!currentDir) {
      continue;
    }

    for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
      const entryPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        pending.push(entryPath);
        continue;
      }
      if (!entry.isFile() || path.extname(entry.name) !== '.md' || entryPath === README_PATH) {
        continue;
      }

      const original = fs.readFileSync(entryPath, 'utf8');
      const firstHeading = original.match(/^# (.+)$/m);
      if (!firstHeading?.[1] || firstHeading.index === undefined) {
        continue;
      }

      const title = firstHeading[1];
      const afterHeading = original
        .slice(firstHeading.index + firstHeading[0].length)
        .replace(/^\n+/, '');
      fs.writeFileSync(entryPath, buildGeneratedPageFrontmatter(title) + afterHeading, 'utf8');
    }
  }
}

rewriteReadme();
rewriteGeneratedPages();
