/**
 * MCP Bridge Orchestration
 *
 * Main entry point for MCP module - handles setup and initialization of MCP bridge.
 */

import type { ChildProcess } from 'child_process';

import logger from '../../logger';
import { startFilesystemMcpServer } from './filesystem';
import { SocketIoMcpBridge } from './transport';
import type { Socket } from 'socket.io-client';

/**
 * Result of MCP bridge setup
 */
export interface McpBridgeSetup {
  mcpProcess: ChildProcess;
  mcpBridge: SocketIoMcpBridge;
  sessionId: string;
}

/**
 * Set up MCP bridge for filesystem access
 *
 * Creates a filesystem MCP server, bridges it with Socket.IO, and announces
 * the runner to the server with the session ID and repository root.
 *
 * @param socket - Connected Socket.IO socket
 * @param absoluteRepoPath - Absolute path to repository root
 * @param sessionId - Session ID to use (generated by caller)
 * @returns MCP bridge setup result
 */
export async function setupMcpBridge(
  socket: Socket,
  absoluteRepoPath: string,
  sessionId: string,
): Promise<McpBridgeSetup> {
  logger.debug('Setting up repo MCP access...');
  logger.debug(`Using session ID: ${sessionId}`);

  // Start filesystem MCP server
  const mcpProcess = startFilesystemMcpServer(absoluteRepoPath);

  // Create MCP bridge using existing socket
  const mcpBridge = new SocketIoMcpBridge(mcpProcess, socket, sessionId);
  await mcpBridge.connect();

  // Announce as runner with repository root for MCP roots/list
  socket.emit('runner:hello', {
    session_id: sessionId,
    repo_root: absoluteRepoPath,
  });

  return {
    mcpProcess,
    mcpBridge,
    sessionId,
  };
}
