// This file is a placeholder for development.
// During build, it gets overwritten with the actual PostHog key.
// DO NOT edit this file manually - changes will be lost during build.

export const POSTHOG_KEY = process.env.PROMPTFOO_POSTHOG_KEY || '';
