import 'prismjs/components/prism-http';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-yaml';
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-javascript';
import 'prismjs/themes/prism.css';

import React from 'react';

import Box from '@mui/material/Box';
import Tab from '@mui/material/Tab';
import Tabs from '@mui/material/Tabs';
import Typography from '@mui/material/Typography';
import TestTargetConfiguration from './TestTargetConfiguration';
import DigitalSignatureAuthTab from './tabs/DigitalSignatureAuthTab';
import HttpStatusCodeTab from './tabs/HttpStatusCodeTab';
import RequestTransformTab from './tabs/RequestTransformTab';
import SessionsTab from './tabs/SessionsTab';
import TlsHttpsConfigTab from './tabs/TlsHttpsConfigTab';
import TokenEstimationTab from './tabs/TokenEstimationTab';
import type { ProviderOptions } from '@promptfoo/types';

interface HttpAdvancedConfigurationProps {
  selectedTarget: ProviderOptions;
  updateCustomTarget: (field: string, value: any) => void;
  defaultRequestTransform?: string;
  onTargetTested?: (success: boolean) => void;
  onSessionTested?: (success: boolean) => void;
}

// TabPanel component for tab content
interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`advanced-tabpanel-${index}`}
      aria-labelledby={`advanced-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ py: 3 }}>{children}</Box>}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `advanced-tab-${index}`,
    'aria-controls': `advanced-tabpanel-${index}`,
  };
}

const HttpAdvancedConfiguration = ({
  selectedTarget,
  defaultRequestTransform,
  updateCustomTarget,
  onTargetTested,
  onSessionTested,
}: HttpAdvancedConfigurationProps) => {
  // Tab state management
  const [activeTab, setActiveTab] = React.useState(0);

  const handleTabChange = (_event: React.SyntheticEvent, newValue: number) => {
    setActiveTab(newValue);
  };

  return (
    <>
      <TestTargetConfiguration selectedTarget={selectedTarget} onTestComplete={onTargetTested} />

      {/* Session Management Section */}
      <Box mt={4} mb={4}>
        <Typography variant="h6" gutterBottom sx={{ mb: 2 }}>
          Conversation State & Session Management
        </Typography>

        <Typography variant="body2" color="textSecondary" sx={{ mb: 3 }}>
          Configure how your target application manages conversation state and sessions. First,
          specify whether your system maintains conversation history across messages. Then configure
          how session IDs are handled - whether they're generated by your server or client-side, and
          how to extract or provide session identifiers. This ensures proper context management
          across multiple interactions.
        </Typography>

        <Box
          sx={{
            p: 3,
            border: 1,
            borderColor: 'divider',
            borderRadius: 1,
            backgroundColor: 'background.paper',
          }}
        >
          <SessionsTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
            onTestComplete={onSessionTested}
          />
        </Box>
      </Box>

      {/* Advanced Configuration Section */}
      <Box mt={4}>
        <Typography variant="h6" gutterBottom sx={{ mb: 3 }}>
          Advanced Configuration
        </Typography>

        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tabs
            value={activeTab}
            onChange={handleTabChange}
            aria-label="advanced configuration tabs"
            variant="scrollable"
            scrollButtons="auto"
          >
            <Tab label="Request Transform" {...a11yProps(0)} />
            <Tab label="Token Estimation" {...a11yProps(1)} />
            <Tab label="Digital Signature Auth" {...a11yProps(2)} />
            <Tab label="TLS/HTTPS Config" {...a11yProps(3)} />
            <Tab label="HTTP Status Code" {...a11yProps(4)} />
          </Tabs>
        </Box>

        {/* Request Transform Tab */}
        <TabPanel value={activeTab} index={0}>
          <RequestTransformTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
            defaultRequestTransform={defaultRequestTransform}
          />
        </TabPanel>

        {/* Token Estimation Tab */}
        <TabPanel value={activeTab} index={1}>
          <TokenEstimationTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
          />
        </TabPanel>

        {/* Digital Signature Authentication Tab */}
        <TabPanel value={activeTab} index={2}>
          <DigitalSignatureAuthTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
          />
        </TabPanel>

        {/* TLS/HTTPS Configuration Tab */}
        <TabPanel value={activeTab} index={3}>
          <TlsHttpsConfigTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
          />
        </TabPanel>

        {/* HTTP Status Code Tab */}
        <TabPanel value={activeTab} index={4}>
          <HttpStatusCodeTab
            selectedTarget={selectedTarget}
            updateCustomTarget={updateCustomTarget}
          />
        </TabPanel>
      </Box>
    </>
  );
};

export default HttpAdvancedConfiguration;
